version: '3'
services:
  app:
    image: visorurbano-backend
    ports:
      - 8812:80
    volumes:
      - ./:/var/www/html
    depends_on:
      - db

    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - networVisorcuernavaca

  db:
    image: kartoza/postgis:16-3.2 
    #se realiza un Upgrade de kartoza/postgis:14-3.2 a kartoza/postgis:16-3.4
    #para que permite tomar la bd postgis que se descargó de AWS y se integre a ambiente pruebas local
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      # NOTA: MODIFICA ESTA LÍNEA DE ABAJO CON FECHA 29 JULIO 2026:
      # SE INHABILITA: - POSTGRES_DB=mydatabase Y SE HABILITA: - POSTGRES_DB=vutramites
      #- POSTGRES_DB=mydatabase
      - POSTGRES_DB=vutramites
    ports:
      - 5412:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - networVisorcuernavaca

networks:
  networVisorcuernavaca:
    driver: bridge
