<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CampoConstruccionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        DB::table('campos_construccion')->insert(
            [
                [
                    'name' => 'int_tipo_persona',
                    'type' => 'radio',
                    'description' => 'Tipo persona',
                    'description_rec' => '',
                    'fundamento' => '',
                    'opciones' => 'Fisica|Moral',
                    'opciones_desc' => 'fisica|moral',
                    'step' => 1,
                    'secuencia' => 1,
                    'requerido' => 1,
                    'tipo_tramite' => 'oficial',
                    'status' => 1,
                    'id_municipio' => 0, 'editable' => 0,
                    'campo_estatico' => 0
                ],
                [
                    'name' => 'int_nombre',
                    'type' => 'input',
                    'description' => 'Nombre(s)',
                    'description_rec' => '|+|',
                    'fundamento' => '',
                    'opciones' => '',
                    'opciones_desc' => '',
                    'step' => 1,
                    'secuencia' => 2,
                    'requerido' => 1,
                    'tipo_tramite' => 'oficial',
                    'status' => 1,
                    'id_municipio' => 0,
                    'editable' => 0,
                    'campo_estatico' => 0,
                ],
                [
                    'name' => 'int_apellidouno',
                    'type' => 'input',
                    'description' => 'Primer apellido',
                    'description_rec' => '|+|',
                    'fundamento' => '',
                    'opciones' => '',
                    'opciones_desc' => '',
                    'step' => 1,
                    'secuencia' => 3,
                    'requerido' => 1,
                    'tipo_tramite' => 'oficial',
                    'status' => 1,
                    'id_municipio' => 0,
                    'editable' => 0,
                    'campo_estatico' => 0,
                ],
                [
                    'name' => 'int_apellidodos',
                    'type' => 'input',
                    'description' => 'Segundo apellido',
                    'description_rec' => '|+|',
                    'fundamento' => '',
                    'opciones' => '',
                    'opciones_desc' => '',
                    'step' => 1,
                    'secuencia' => 4,
                    'requerido' => 1,
                    'tipo_tramite' => 'oficial',
                    'status' => 1,
                    'id_municipio' => 0,
                    'editable' => 0,
                    'campo_estatico' => 0,
                ],
                [
                    'name' => 'int_curp',
                    'type' => 'input',
                    'description' => 'CURP',
                    'description_rec' => '|+|',
                    'fundamento' => '',
                    'opciones' => '',
                    'opciones_desc' => '',
                    'step' => 1,
                    'secuencia' => 5,
                    'requerido' => 1,
                    'tipo_tramite' => 'oficial',
                    'status' => 1,
                    'id_municipio' => 0,
                    'editable' => 0,
                    'campo_estatico' => 0,
                ],
                [
                    'name' => 'int_rfc',
                    'type' => 'input',
                    'description' => 'RFC',
                    'description_rec' => '|+|',
                    'fundamento' => '',
                    'opciones' => '',
                    'opciones_desc' => '',
                    'step' => 1,
                    'secuencia' => 6,
                    'requerido' => 1,
                    'tipo_tramite' => 'oficial',
                    'status' => 1,
                    'id_municipio' => 0,
                    'editable' => 0,
                    'campo_estatico' => 0,
                ],
                [
                    'name' => 'int_correo',
                    'type' => 'input',
                    'description' => 'Correo electrónico',
                    'description_rec' => '|+|',
                    'fundamento' => '',
                    'opciones' => '',
                    'opciones_desc' => '',
                    'step' => 1,
                    'secuencia' => 7,
                    'requerido' => 1,
                    'tipo_tramite' => 'oficial',
                    'status' => 1,
                    'id_municipio' => 0,
                    'editable' => 0,
                    'campo_estatico' => 0,
                ],
                [
                    'name' => 'int_cel',
                    'type' => 'input',
                    'description' => 'Celular',
                    'description_rec' => '|+|',
                    'fundamento' => '',
                    'opciones' => '',
                    'opciones_desc' => '',
                    'step' => 1,
                    'secuencia' => 8,
                    'requerido' => 1,
                    'tipo_tramite' => 'oficial',
                    'status' => 1,
                    'id_municipio' => 0,
                    'editable' => 0,
                    'campo_estatico' => 0,
                ],
                [
                    'name' => 'int_calle',
                    'type' => 'input',
                    'description' => 'Calle',
                    'description_rec' => '|+|',
                    'fundamento' => '',
                    'opciones' => '',
                    'opciones_desc' => '',
                    'step' => 1,
                    'secuencia' => 9,
                    'requerido' => 1,
                    'tipo_tramite' => 'oficial',
                    'status' => 1,
                    'id_municipio' => 0,
                    'editable' => 0,
                    'campo_estatico' => 0,
                ],
                [
                    'name' => 'int_no_ext',
                    'type' => 'input',
                    'description' => 'Número y/o letra exterior',
                    'description_rec' => '|+|',
                    'fundamento' => '',
                    'opciones' => '',
                    'opciones_desc' => '',
                    'step' => 1,
                    'secuencia' => 10,
                    'requerido' => 1,
                    'tipo_tramite' => 'oficial',
                    'status' => 1,
                    'id_municipio' => 0,
                    'editable' => 0,
                    'campo_estatico' => 0,
                ],
                [
                    'name' => 'int_no_int',
                    'type' => 'input',
                    'description' => 'Número y/o letra interior',
                    'description_rec' => '|+|',
                    'fundamento' => '',
                    'opciones' => '',
                    'opciones_desc' => '',
                    'step' => 1,
                    'secuencia' => 11,
                    'requerido' => 1,
                    'tipo_tramite' => 'oficial',
                    'status' => 1,
                    'id_municipio' => 0,
                    'editable' => 0,
                    'campo_estatico' => 0,
                ],
                [
                    'name' => 'int_colonia',
                    'type' => 'input',
                    'description' => 'Colonia',
                    'description_rec' => '|+|',
                    'fundamento' => '',
                    'opciones' => '',
                    'opciones_desc' => '',
                    'step' => 1,
                    'secuencia' => 12,
                    'requerido' => 1,
                    'tipo_tramite' => 'oficial',
                    'status' => 1,
                    'id_municipio' => 0,
                    'editable' => 0,
                    'campo_estatico' => 0,
                ],
                [
                    'name' => 'int_localidad',
                    'type' => 'input',
                    'description' => 'Localidad',
                    'description_rec' => '|+|',
                    'fundamento' => '',
                    'opciones' => '',
                    'opciones_desc' => '',
                    'step' => 1,
                    'secuencia' => 13,
                    'requerido' => 1,
                    'tipo_tramite' => 'oficial',
                    'status' => 1,
                    'id_municipio' => 0,
                    'editable' => 0,
                    'campo_estatico' => 0,
                ],
                [
                    'name' => 'int_mpio',
                    'type' => 'input',
                    'description' => 'Municipio',
                    'description_rec' => '|+|',
                    'fundamento' => '',
                    'opciones' => '',
                    'opciones_desc' => '',
                    'step' => 1,
                    'secuencia' => 14,
                    'requerido' => 1,
                    'tipo_tramite' => 'oficial',
                    'status' => 1,
                    'id_municipio' => 0,
                    'editable' => 0,
                    'campo_estatico' => 0,
                ],
                [
                    'name' => 'int_cp',
                    'type' => 'input',
                    'description' => 'CP',
                    'description_rec' => '|+|',
                    'fundamento' => '',
                    'opciones' => '',
                    'opciones_desc' => '',
                    'step' => 1,
                    'secuencia' => 15,
                    'requerido' => 1,
                    'tipo_tramite' => 'oficial',
                    'status' => 1,
                    'id_municipio' => 0,
                    'editable' => 0,
                    'campo_estatico' => 0,
                ],
                [
                    'name' => 'int_moral_rsocial',
                    'type' => 'input',
                    'description' => 'Razón Social',
                    'description_rec' => '|+|',
                    'fundamento' => '',
                    'opciones' => '',
                    'opciones_desc' => '',
                    'step' => 1,
                    'secuencia' => 16,
                    'requerido' => 1,
                    'tipo_tramite' => 'oficial',
                    'status' => 1,
                    'id_municipio' => 0,
                    'editable' => 0,
                    'campo_estatico' => 0,
                ],
                [
                    'name' => 'int_moral_rfc',
                    'type' => 'input',
                    'description' => 'RFC',
                    'description_rec' => '|+|',
                    'fundamento' => '',
                    'opciones' => '',
                    'opciones_desc' => '',
                    'step' => 1,
                    'secuencia' => 17,
                    'requerido' => 1,
                    'tipo_tramite' => 'oficial',
                    'status' => 1,
                    'id_municipio' => 0,
                    'editable' => 0,
                    'campo_estatico' => 0,
                ],
                [
                    'name' => 'int_moral_calle',
                    'type' => 'input',
                    'description' => 'Calle',
                    'description_rec' => '|+|',
                    'fundamento' => '',
                    'opciones' => '',
                    'opciones_desc' => '',
                    'step' => 1,
                    'secuencia' => 18,
                    'requerido' => 1,
                    'tipo_tramite' => 'oficial',
                    'status' => 1,
                    'id_municipio' => 0,
                    'editable' => 0,
                    'campo_estatico' => 0,
                ],
                [
                    'name' => 'int_moral_no_ext',
                    'type' => 'input',
                    'description' => 'Número y/o letra exterior',
                    'description_rec' => '|+|',
                    'fundamento' => '',
                    'opciones' => '',
                    'opciones_desc' => '',
                    'step' => 1,
                    'secuencia' => 19,
                    'requerido' => 1,
                    'tipo_tramite' => 'oficial',
                    'status' => 1,
                    'id_municipio' => 0,
                    'editable' => 0,
                    'campo_estatico' => 0,
                ],
                [
                    'name' => 'int_moral_no_int',
                    'type' => 'input',
                    'description' => 'Número y/o letra interior',
                    'description_rec' => '|+|',
                    'fundamento' => '',
                    'opciones' => '',
                    'opciones_desc' => '',
                    'step' => 1,
                    'secuencia' => 20,
                    'requerido' => 1,
                    'tipo_tramite' => 'oficial',
                    'status' => 1,
                    'id_municipio' => 0,
                    'editable' => 0,
                    'campo_estatico' => 0,
                ],
                [
                    'name' => 'int_moral_colonia',
                    'type' => 'input',
                    'description' => 'Colonia',
                    'description_rec' => '|+|',
                    'fundamento' => '',
                    'opciones' => '',
                    'opciones_desc' => '',
                    'step' => 1,
                    'secuencia' => 21,
                    'requerido' => 1,
                    'tipo_tramite' => 'oficial',
                    'status' => 1,
                    'id_municipio' => 0,
                    'editable' => 0,
                    'campo_estatico' => 0,
                ],
                [
                    'name' => 'int_moral_localidad',
                    'type' => 'input',
                    'description' => 'Localidad',
                    'description_rec' => '|+|',
                    'fundamento' => '',
                    'opciones' => '',
                    'opciones_desc' => '',
                    'step' => 1,
                    'secuencia' => 22,
                    'requerido' => 1,
                    'tipo_tramite' => 'oficial',
                    'status' => 1,
                    'id_municipio' => 0,
                    'editable' => 0,
                    'campo_estatico' => 0,
                ],
                [
                    'name' => 'int_moral_mpio',
                    'type' => 'input',
                    'description' => 'Municipio',
                    'description_rec' => '|+|',
                    'fundamento' => '',
                    'opciones' => '',
                    'opciones_desc' => '',
                    'step' => 1,
                    'secuencia' => 23,
                    'requerido' => 1,
                    'tipo_tramite' => 'oficial',
                    'status' => 1,
                    'id_municipio' => 0,
                    'editable' => 0,
                    'campo_estatico' => 0,
                ],
                [
                    'name' => 'int_moral_cp',
                    'type' => 'input',
                    'description' => 'C.P',
                    'description_rec' => '|+|',
                    'fundamento' => '',
                    'opciones' => '',
                    'opciones_desc' => '',
                    'step' => 1,
                    'secuencia' => 24,
                    'requerido' => 1,
                    'tipo_tramite' => 'oficial',
                    'status' => 1,
                    'id_municipio' => 0,
                    'editable' => 0,
                    'campo_estatico' => 0,
                ],
                //Datos Propietario

                [
                    'name' => 'prop_tipo_persona',
                    'type' => 'radio',
                    'description' => 'Tipo persona',
                    'description_rec' => '',
                    'fundamento' => '',
                    'opciones' => 'Fisica|Moral',
                    'opciones_desc' => 'fisica|moral',
                    'step' => 2,
                    'secuencia' => 1,
                    'requerido' => 1,
                    'tipo_tramite' => 'oficial',
                    'status' => 1,
                    'id_municipio' => 0, 'editable' => 0,
                    'campo_estatico' => 0
                ],
                [
                    'name' => 'prop_nombre',
                    'type' => 'input',
                    'description' => 'Nombre(s)',
                    'description_rec' => '|+|',
                    'fundamento' => '',
                    'opciones' => '',
                    'opciones_desc' => '',
                    'step' => 2,
                    'secuencia' => 2,
                    'requerido' => 1,
                    'tipo_tramite' => 'oficial',
                    'status' => 1,
                    'id_municipio' => 0,
                    'editable' => 0,
                    'campo_estatico' => 0,
                ],
                [
                    'name' => 'prop_apellidouno',
                    'type' => 'input',
                    'description' => 'Primer apellido',
                    'description_rec' => '|+|',
                    'fundamento' => '',
                    'opciones' => '',
                    'opciones_desc' => '',
                    'step' => 2,
                    'secuencia' => 3,
                    'requerido' => 1,
                    'tipo_tramite' => 'oficial',
                    'status' => 1,
                    'id_municipio' => 0,
                    'editable' => 0,
                    'campo_estatico' => 0,
                ],
                [
                    'name' => 'prop_apellidodos',
                    'type' => 'input',
                    'description' => 'Segundo apellido',
                    'description_rec' => '|+|',
                    'fundamento' => '',
                    'opciones' => '',
                    'opciones_desc' => '',
                    'step' => 2,
                    'secuencia' => 4,
                    'requerido' => 1,
                    'tipo_tramite' => 'oficial',
                    'status' => 1,
                    'id_municipio' => 0,
                    'editable' => 0,
                    'campo_estatico' => 0,
                ],
                [
                    'name' => 'prop_curp',
                    'type' => 'input',
                    'description' => 'CURP',
                    'description_rec' => '|+|',
                    'fundamento' => '',
                    'opciones' => '',
                    'opciones_desc' => '',
                    'step' => 2,
                    'secuencia' => 5,
                    'requerido' => 1,
                    'tipo_tramite' => 'oficial',
                    'status' => 1,
                    'id_municipio' => 0,
                    'editable' => 0,
                    'campo_estatico' => 0,
                ],
                [
                    'name' => 'prop_rfc',
                    'type' => 'input',
                    'description' => 'RFC',
                    'description_rec' => '|+|',
                    'fundamento' => '',
                    'opciones' => '',
                    'opciones_desc' => '',
                    'step' => 2,
                    'secuencia' => 6,
                    'requerido' => 1,
                    'tipo_tramite' => 'oficial',
                    'status' => 1,
                    'id_municipio' => 0,
                    'editable' => 0,
                    'campo_estatico' => 0,
                ],
                [
                    'name' => 'prop_correo',
                    'type' => 'input',
                    'description' => 'Correo electrónico',
                    'description_rec' => '|+|',
                    'fundamento' => '',
                    'opciones' => '',
                    'opciones_desc' => '',
                    'step' => 2,
                    'secuencia' => 7,
                    'requerido' => 1,
                    'tipo_tramite' => 'oficial',
                    'status' => 1,
                    'id_municipio' => 0,
                    'editable' => 0,
                    'campo_estatico' => 0,
                ],
                [
                    'name' => 'prop_cel',
                    'type' => 'input',
                    'description' => 'Celular',
                    'description_rec' => '|+|',
                    'fundamento' => '',
                    'opciones' => '',
                    'opciones_desc' => '',
                    'step' => 2,
                    'secuencia' => 8,
                    'requerido' => 1,
                    'tipo_tramite' => 'oficial',
                    'status' => 1,
                    'id_municipio' => 0,
                    'editable' => 0,
                    'campo_estatico' => 0,
                ],
                [
                    'name' => 'prop_calle',
                    'type' => 'input',
                    'description' => 'Calle',
                    'description_rec' => '|+|',
                    'fundamento' => '',
                    'opciones' => '',
                    'opciones_desc' => '',
                    'step' => 2,
                    'secuencia' => 9,
                    'requerido' => 1,
                    'tipo_tramite' => 'oficial',
                    'status' => 1,
                    'id_municipio' => 0,
                    'editable' => 0,
                    'campo_estatico' => 0,
                ],
                [
                    'name' => 'prop_no_ext',
                    'type' => 'input',
                    'description' => 'Número y/o letra exterior',
                    'description_rec' => '|+|',
                    'fundamento' => '',
                    'opciones' => '',
                    'opciones_desc' => '',
                    'step' => 2,
                    'secuencia' => 10,
                    'requerido' => 1,
                    'tipo_tramite' => 'oficial',
                    'status' => 1,
                    'id_municipio' => 0,
                    'editable' => 0,
                    'campo_estatico' => 0,
                ],
                [
                    'name' => 'prop_no_int',
                    'type' => 'input',
                    'description' => 'Número y/o letra interior',
                    'description_rec' => '|+|',
                    'fundamento' => '',
                    'opciones' => '',
                    'opciones_desc' => '',
                    'step' => 2,
                    'secuencia' => 11,
                    'requerido' => 1,
                    'tipo_tramite' => 'oficial',
                    'status' => 1,
                    'id_municipio' => 0,
                    'editable' => 0,
                    'campo_estatico' => 0,
                ],
                [
                    'name' => 'prop_colonia',
                    'type' => 'input',
                    'description' => 'Colonia',
                    'description_rec' => '|+|',
                    'fundamento' => '',
                    'opciones' => '',
                    'opciones_desc' => '',
                    'step' => 2,
                    'secuencia' => 12,
                    'requerido' => 1,
                    'tipo_tramite' => 'oficial',
                    'status' => 1,
                    'id_municipio' => 0,
                    'editable' => 0,
                    'campo_estatico' => 0,
                ],
                [
                    'name' => 'prop_localidad',
                    'type' => 'input',
                    'description' => 'Localidad',
                    'description_rec' => '|+|',
                    'fundamento' => '',
                    'opciones' => '',
                    'opciones_desc' => '',
                    'step' => 2,
                    'secuencia' => 13,
                    'requerido' => 1,
                    'tipo_tramite' => 'oficial',
                    'status' => 1,
                    'id_municipio' => 0,
                    'editable' => 0,
                    'campo_estatico' => 0,
                ],
                [
                    'name' => 'prop_mpio',
                    'type' => 'input',
                    'description' => 'Municipio',
                    'description_rec' => '|+|',
                    'fundamento' => '',
                    'opciones' => '',
                    'opciones_desc' => '',
                    'step' => 2,
                    'secuencia' => 14,
                    'requerido' => 1,
                    'tipo_tramite' => 'oficial',
                    'status' => 1,
                    'id_municipio' => 0,
                    'editable' => 0,
                    'campo_estatico' => 0,
                ],
                [
                    'name' => 'prop_cp',
                    'type' => 'input',
                    'description' => 'C.P.',
                    'description_rec' => '|+|',
                    'fundamento' => '',
                    'opciones' => '',
                    'opciones_desc' => '',
                    'step' => 2,
                    'secuencia' => 15,
                    'requerido' => 1,
                    'tipo_tramite' => 'oficial',
                    'status' => 1,
                    'id_municipio' => 0,
                    'editable' => 0,
                    'campo_estatico' => 0,
                ],

                //Si el propietario es persona moral llenar los siguientes datos:
                [
                    'name' => 'propmoral_rsocial',
                    'type' => 'input',
                    'description' => 'Razón social',
                    'description_rec' => '|+|',
                    'fundamento' => '',
                    'opciones' => '',
                    'opciones_desc' => '',
                    'step' => 2,
                    'secuencia' => 16,
                    'requerido' => 1,
                    'tipo_tramite' => 'oficial',
                    'status' => 1,
                    'id_municipio' => 0,
                    'editable' => 0,
                    'campo_estatico' => 0,
                ],
                [
                    'name' => 'propmoral_rfc',
                    'type' => 'input',
                    'description' => 'RFC',
                    'description_rec' => '|+|',
                    'fundamento' => '',
                    'opciones' => '',
                    'opciones_desc' => '',
                    'step' => 2,
                    'secuencia' => 17,
                    'requerido' => 1,
                    'tipo_tramite' => 'oficial',
                    'status' => 1,
                    'id_municipio' => 0,
                    'editable' => 0,
                    'campo_estatico' => 0,
                ],
                [
                    'name' => 'propmoral_calle',
                    'type' => 'input',
                    'description' => 'Calle',
                    'description_rec' => '|+|',
                    'fundamento' => '',
                    'opciones' => '',
                    'opciones_desc' => '',
                    'step' => 2,
                    'secuencia' => 18,
                    'requerido' => 1,
                    'tipo_tramite' => 'oficial',
                    'status' => 1,
                    'id_municipio' => 0,
                    'editable' => 0,
                    'campo_estatico' => 0,
                ],
                [
                    'name' => 'propmoral_no_ext',
                    'type' => 'input',
                    'description' => 'Número y/o letra exterior',
                    'description_rec' => '|+|',
                    'fundamento' => '',
                    'opciones' => '',
                    'opciones_desc' => '',
                    'step' => 2,
                    'secuencia' => 19,
                    'requerido' => 1,
                    'tipo_tramite' => 'oficial',
                    'status' => 1,
                    'id_municipio' => 0,
                    'editable' => 0,
                    'campo_estatico' => 0,
                ],
                [
                    'name' => 'propmoral_no_int',
                    'type' => 'input',
                    'description' => 'Número y/o letra interior',
                    'description_rec' => '|+|',
                    'fundamento' => '',
                    'opciones' => '',
                    'opciones_desc' => '',
                    'step' => 2,
                    'secuencia' => 20,
                    'requerido' => 1,
                    'tipo_tramite' => 'oficial',
                    'status' => 1,
                    'id_municipio' => 0,
                    'editable' => 0,
                    'campo_estatico' => 0,
                ],
                [
                    'name' => 'propmoral_colonia',
                    'type' => 'input',
                    'description' => 'Colonia',
                    'description_rec' => '|+|',
                    'fundamento' => '',
                    'opciones' => '',
                    'opciones_desc' => '',
                    'step' => 2,
                    'secuencia' => 21,
                    'requerido' => 1,
                    'tipo_tramite' => 'oficial',
                    'status' => 1,
                    'id_municipio' => 0,
                    'editable' => 0,
                    'campo_estatico' => 0,
                ],
                [
                    'name' => 'propmoral_localidad',
                    'type' => 'input',
                    'description' => 'Localidad',
                    'description_rec' => '|+|',
                    'fundamento' => '',
                    'opciones' => '',
                    'opciones_desc' => '',
                    'step' => 2,
                    'secuencia' => 22,
                    'requerido' => 1,
                    'tipo_tramite' => 'oficial',
                    'status' => 1,
                    'id_municipio' => 0,
                    'editable' => 0,
                    'campo_estatico' => 0,
                ],
                [
                    'name' => 'propmoral_mpio',
                    'type' => 'input',
                    'description' => 'Municipio',
                    'description_rec' => '|+|',
                    'fundamento' => '',
                    'opciones' => '',
                    'opciones_desc' => '',
                    'step' => 2,
                    'secuencia' => 23,
                    'requerido' => 1,
                    'tipo_tramite' => 'oficial',
                    'status' => 1,
                    'id_municipio' => 0,
                    'editable' => 0,
                    'campo_estatico' => 0,
                ],
                [
                    'name' => 'propmoral_cp',
                    'type' => 'input',
                    'description' => 'C.P.',
                    'description_rec' => '|+|',
                    'fundamento' => '',
                    'opciones' => '',
                    'opciones_desc' => '',
                    'step' => 2,
                    'secuencia' => 24,
                    'requerido' => 1,
                    'tipo_tramite' => 'oficial',
                    'status' => 1,
                    'id_municipio' => 0,
                    'editable' => 0,
                    'campo_estatico' => 0,
                ],
                //Ubicación de la obra:

                [
                    'name' => 'obra_calle',
                    'type' => 'input',
                    'description' => 'Calle',
                    'description_rec' => '|+|',
                    'fundamento' => '',
                    'opciones' => '',
                    'opciones_desc' => '',
                    'step' => 3,
                    'secuencia' => 1,
                    'requerido' => 1,
                    'tipo_tramite' => 'oficial',
                    'status' => 1,
                    'id_municipio' => 0,
                    'editable' => 0,
                    'campo_estatico' => 0,
                ], 
                [
                    'name' => 'entre_calleuno',
                    'type' => 'input',
                    'description' => 'Entre la calle',
                    'description_rec' => '|+|',
                    'fundamento' => '',
                    'opciones' => '',
                    'opciones_desc' => '',
                    'step' => 3,
                    'secuencia' => 1,
                    'requerido' => 1,
                    'tipo_tramite' => 'oficial',
                    'status' => 1,
                    'id_municipio' => 0,
                    'editable' => 0,
                    'campo_estatico' => 0,
                ],
                 [
                    'name' => 'entre_calledos',
                    'type' => 'input',
                    'description' => 'Y la calle',
                    'description_rec' => '|+|',
                    'fundamento' => '',
                    'opciones' => '',
                    'opciones_desc' => '',
                    'step' => 3,
                    'secuencia' => 1,
                    'requerido' => 1,
                    'tipo_tramite' => 'oficial',
                    'status' => 1,
                    'id_municipio' => 0,
                    'editable' => 0,
                    'campo_estatico' => 0,
                ],
                [
                    'name' => 'obra_no_ext',
                    'type' => 'input',
                    'description' => 'Número y/o letra exterior',
                    'description_rec' => '|+|',
                    'fundamento' => '',
                    'opciones' => '',
                    'opciones_desc' => '',
                    'step' => 3,
                    'secuencia' => 2,
                    'requerido' => 1,
                    'tipo_tramite' => 'oficial',
                    'status' => 1,
                    'id_municipio' => 0,
                    'editable' => 0,
                    'campo_estatico' => 0,
                ],
                [
                    'name' => 'obra_no_int',
                    'type' => 'input',
                    'description' => 'Número y/o letra interior',
                    'description_rec' => '|+|',
                    'fundamento' => '',
                    'opciones' => '',
                    'opciones_desc' => '',
                    'step' => 3,
                    'secuencia' => 3,
                    'requerido' => 1,
                    'tipo_tramite' => 'oficial',
                    'status' => 1,
                    'id_municipio' => 0,
                    'editable' => 0,
                    'campo_estatico' => 0,
                ],
                [
                    'name' => 'obra_colonia',
                    'type' => 'input',
                    'description' => 'Colonia',
                    'description_rec' => '|+|',
                    'fundamento' => '',
                    'opciones' => '',
                    'opciones_desc' => '',
                    'step' => 3,
                    'secuencia' => 4,
                    'requerido' => 1,
                    'tipo_tramite' => 'oficial',
                    'status' => 1,
                    'id_municipio' => 0,
                    'editable' => 0,
                    'campo_estatico' => 0,
                ],
                [
                    'name' => 'obra_localidad',
                    'type' => 'input',
                    'description' => 'Localidad',
                    'description_rec' => '|+|',
                    'fundamento' => '',
                    'opciones' => '',
                    'opciones_desc' => '',
                    'step' => 3,
                    'secuencia' => 5,
                    'requerido' => 1,
                    'tipo_tramite' => 'oficial',
                    'status' => 1,
                    'id_municipio' => 0,
                    'editable' => 0,
                    'campo_estatico' => 0,
                ],
                [
                    'name' => 'obra_cp',
                    'type' => 'input',
                    'description' => 'CP',
                    'description_rec' => '|+|',
                    'fundamento' => '',
                    'opciones' => '',
                    'opciones_desc' => '',
                    'step' => 3,
                    'secuencia' => 6,
                    'requerido' => 1,
                    'tipo_tramite' => 'oficial',
                    'status' => 1,
                    'id_municipio' => 0,
                    'editable' => 0,
                    'campo_estatico' => 0,
                ],
                [
                    'name' => 'obra_cta_agua',
                    'type' => 'input',
                    'description' => 'Cuenta agua',
                    'description_rec' => '|+|',
                    'fundamento' => '',
                    'opciones' => '',
                    'opciones_desc' => '',
                    'step' => 3,
                    'secuencia' => 7,
                    'requerido' => 1,
                    'tipo_tramite' => 'oficial',
                    'status' => 1,
                    'id_municipio' => 0,
                    'editable' => 0,
                    'campo_estatico' => 0,
                ],
                [
                    'name' => 'obra_cve_catastral',
                    'type' => 'input',
                    'description' => 'Clave Catastral',
                    'description_rec' => '|+|',
                    'fundamento' => '',
                    'opciones' => '',
                    'opciones_desc' => '',
                    'step' => 3,
                    'secuencia' => 8,
                    'requerido' => 1,
                    'tipo_tramite' => 'oficial',
                    'status' => 1,
                    'id_municipio' => 0,
                    'editable' => 0,
                    'campo_estatico' => 0,
                ],
                [
                    'name' => 'obra_cta_predial',
                    'type' => 'input',
                    'description' => 'Cuenta predial',
                    'description_rec' => '|+|',
                    'fundamento' => '',
                    'opciones' => '',
                    'opciones_desc' => '',
                    'step' => 3,
                    'secuencia' => 9,
                    'requerido' => 1,
                    'tipo_tramite' => 'oficial',
                    'status' => 1,
                    'id_municipio' => 0,
                    'editable' => 0,
                    'campo_estatico' => 0,
                ],
                [
                    'name' => 'tipo_dcto_propiedad',
                    'type' => 'select',
                    'description' => 'Documento que acredita la propiedad:',
                    'description_rec' => '',
                    'fundamento' => '',
                    'opciones' => 'Escritura|Título de propiedad|Certificado parcelario|Contrato arrendamiento|Otro',
                    'opciones_desc' => '1|2|3|4|5',
                    'step' => 3,
                    'secuencia' => 10,
                    'requerido' => 1,
                    'tipo_tramite' => 'oficial',
                    'status' => 1,
                    'id_municipio' => 0, 'editable' => 0,
                    'campo_estatico' => 0
                ],
                [
                    'name' => 'tipo_dcto_propiedad_otro',
                    'type' => 'input',
                    'description' => 'Otro',
                    'description_rec' => '|+|',
                    'fundamento' => '',
                    'opciones' => '',
                    'opciones_desc' => '',
                    'step' => 3,
                    'secuencia' => 11,
                    'requerido' => 1,
                    'tipo_tramite' => 'oficial',
                    'status' => 1,
                    'id_municipio' => 0,
                    'editable' => 0,
                    'campo_estatico' => 0,
                ],
                [
                    'name' => 'no_dcto_propiedad',
                    'type' => 'input',
                    'description' => 'No. de documento',
                    'description_rec' => '|+|',
                    'fundamento' => '',
                    'opciones' => '',
                    'opciones_desc' => '',
                    'step' => 3,
                    'secuencia' => 12,
                    'requerido' => 1,
                    'tipo_tramite' => 'oficial',
                    'status' => 1,
                    'id_municipio' => 0,
                    'editable' => 0,
                    'campo_estatico' => 0,
                ],
                [
                    'name' => 'fedatario_publico',
                    'type' => 'select',
                    'description' => 'Fedatario público',
                    'description_rec' => '',
                    'fundamento' => '',
                    'opciones' => 'Registro Agrario Nacional|CORETT|Otro|Notario público',
                    'opciones_desc' => '1|2|3|4',
                    'step' => 3,
                    'secuencia' => 13,
                    'requerido' => 1,
                    'tipo_tramite' => 'oficial',
                    'status' => 1,
                    'id_municipio' => 0, 'editable' => 0,
                    'campo_estatico' => 0
                ],
                [
                    'name' => 'notario_publico',
                    'type' => 'select',
                    'description' => 'Notario Público',
                    'description_rec' => '',
                    'fundamento' => '',
                    'opciones' => '',
                    'opciones_desc' => '',
                    'step' => 3,
                    'secuencia' => 14,
                    'requerido' => 1,
                    'tipo_tramite' => 'oficial',
                    'status' => 1,
                    'id_municipio' => 0, 'editable' => 0,
                    'campo_estatico' => 0
                ],
                [
                    'name' => 'fedatario_publico_otro',
                    'type' => 'input',
                    'description' => 'Otro',
                    'description_rec' => '|+|',
                    'fundamento' => '',
                    'opciones' => '',
                    'opciones_desc' => '',
                    'step' => 3,
                    'secuencia' => 15,
                    'requerido' => 1,
                    'tipo_tramite' => 'oficial',
                    'status' => 1,
                    'id_municipio' => 0, 'editable' => 0,
                    'campo_estatico' => 0
                ],      
                [
                    'name' => 'fecha_dcto_propiedad',
                    'type' => 'input',
                    'description' => 'Fecha de expedición',
                    'description_rec' => '|+|',
                    'fundamento' => '',
                    'opciones' => '',
                    'opciones_desc' => '',
                    'step' => 3,
                    'secuencia' => 16,
                    'requerido' => 1,
                    'tipo_tramite' => 'oficial',
                    'status' => 1,
                    'id_municipio' => 0,
                    'editable' => 0,
                    'campo_estatico' => 0,
                ],
              
                
                //Director Responsable e dObra o proyecto
                [
                    'name' => 'dro_requiere',
                    'type' => 'radio',
                    'description' => 'Requiere Perito / Consultor',
                    'description_rec' => '',
                    'fundamento' => '',
                    'opciones' => 'Si|No',
                    'opciones_desc' => 'si|no',
                    'step' => 4,
                    'secuencia' => 1,
                    'requerido' => 1,
                    'tipo_tramite' => 'oficial',
                    'status' => 1,
                    'id_municipio' => 0, 
                    'editable' => 0,
                    'campo_estatico' => 0
                ],
                [
                    'name' => 'dro_nombre',
                    'type' => 'input',
                    'description' => 'Nombre(s)',
                    'description_rec' => '|+|',
                    'fundamento' => '',
                    'opciones' => '',
                    'opciones_desc' => '',
                    'step' => 4,
                    'secuencia' => 2,
                    'requerido' => 1,
                    'tipo_tramite' => 'oficial',
                    'status' => 1,
                    'id_municipio' => 0,
                    'editable' => 0,
                    'campo_estatico' => 0,
                ],
                [
                    'name' => 'dro_apellidouno',
                    'type' => 'input',
                    'description' => 'Primer apellido',
                    'description_rec' => '|+|',
                    'fundamento' => '',
                    'opciones' => '',
                    'opciones_desc' => '',
                    'step' => 4,
                    'secuencia' => 3,
                    'requerido' => 1,
                    'tipo_tramite' => 'oficial',
                    'status' => 1,
                    'id_municipio' => 0,
                    'editable' => 0,
                    'campo_estatico' => 0,
                ],
                [
                    'name' => 'dro_apellidodos',
                    'type' => 'input',
                    'description' => 'Segundo apellido',
                    'description_rec' => '|+|',
                    'fundamento' => '',
                    'opciones' => '',
                    'opciones_desc' => '',
                    'step' => 4,
                    'secuencia' => 4,
                    'requerido' => 1,
                    'tipo_tramite' => 'oficial',
                    'status' => 1,
                    'id_municipio' => 0,
                    'editable' => 0,
                    'campo_estatico' => 0,
                ],
                [
                    'name' => 'dro_curp',
                    'type' => 'input',
                    'description' => 'CURP',
                    'description_rec' => '|+|',
                    'fundamento' => '',
                    'opciones' => '',
                    'opciones_desc' => '',
                    'step' => 4,
                    'secuencia' => 5,
                    'requerido' => 1,
                    'tipo_tramite' => 'oficial',
                    'status' => 1,
                    'id_municipio' => 0,
                    'editable' => 0,
                    'campo_estatico' => 0,
                ],
                [
                    'name' => 'dro_no_registro',
                    'type' => 'input',
                    'description' => 'Registro de Perito / Consultor',
                    'description_rec' => '|+|',
                    'fundamento' => '',
                    'opciones' => '',
                    'opciones_desc' => '',
                    'step' => 4,
                    'secuencia' => 6,
                    'requerido' => 1,
                    'tipo_tramite' => 'oficial',
                    'status' => 1,
                    'id_municipio' => 0,
                    'editable' => 0,
                    'campo_estatico' => 0,
                ],
                [
                    'name' => 'dro_rfc',
                    'type' => 'input',
                    'description' => 'RFC',
                    'description_rec' => '|+|',
                    'fundamento' => '',
                    'opciones' => '',
                    'opciones_desc' => '',
                    'step' => 4,
                    'secuencia' => 7,
                    'requerido' => 1,
                    'tipo_tramite' => 'oficial',
                    'status' => 1,
                    'id_municipio' => 0,
                    'editable' => 0,
                    'campo_estatico' => 0,
                ],
                [
                    'name' => 'dro_correo',
                    'type' => 'input',
                    'description' => 'Correo electrónico',
                    'description_rec' => '|+|',
                    'fundamento' => '',
                    'opciones' => '',
                    'opciones_desc' => '',
                    'step' => 4,
                    'secuencia' => 8,
                    'requerido' => 1,
                    'tipo_tramite' => 'oficial',
                    'status' => 1,
                    'id_municipio' => 0,
                    'editable' => 0,
                    'campo_estatico' => 0,
                ],
                [
                    'name' => 'dro_cel',
                    'type' => 'input',
                    'description' => 'Celular',
                    'description_rec' => '|+|',
                    'fundamento' => '',
                    'opciones' => '',
                    'opciones_desc' => '',
                    'step' => 4,
                    'secuencia' => 9,
                    'requerido' => 1,
                    'tipo_tramite' => 'oficial',
                    'status' => 1,
                    'id_municipio' => 0,
                    'editable' => 0,
                    'campo_estatico' => 0,
                ],
                [
                    'name' => 'dro_calle',
                    'type' => 'input',
                    'description' => 'Calle',
                    'description_rec' => '|+|',
                    'fundamento' => '',
                    'opciones' => '',
                    'opciones_desc' => '',
                    'step' => 4,
                    'secuencia' => 10,
                    'requerido' => 1,
                    'tipo_tramite' => 'oficial',
                    'status' => 1,
                    'id_municipio' => 0,
                    'editable' => 0,
                    'campo_estatico' => 0,
                ],
                [
                    'name' => 'dro_no_ext',
                    'type' => 'input',
                    'description' => 'Número y/o letra exterior',
                    'description_rec' => '|+|',
                    'fundamento' => '',
                    'opciones' => '',
                    'opciones_desc' => '',
                    'step' => 4,
                    'secuencia' => 11,
                    'requerido' => 1,
                    'tipo_tramite' => 'oficial',
                    'status' => 1,
                    'id_municipio' => 0,
                    'editable' => 0,
                    'campo_estatico' => 0,
                ],
                [
                    'name' => 'dro_no_int',
                    'type' => 'input',
                    'description' => 'Número y/o letra interior',
                    'description_rec' => '|+|',
                    'fundamento' => '',
                    'opciones' => '',
                    'opciones_desc' => '',
                    'step' => 4,
                    'secuencia' => 12,
                    'requerido' => 1,
                    'tipo_tramite' => 'oficial',
                    'status' => 1,
                    'id_municipio' => 0,
                    'editable' => 0,
                    'campo_estatico' => 0,
                ],
                [
                    'name' => 'dro_colonia',
                    'type' => 'input',
                    'description' => 'Colonia',
                    'description_rec' => '|+|',
                    'fundamento' => '',
                    'opciones' => '',
                    'opciones_desc' => '',
                    'step' => 4,
                    'secuencia' => 13,
                    'requerido' => 1,
                    'tipo_tramite' => 'oficial',
                    'status' => 1,
                    'id_municipio' => 0,
                    'editable' => 0,
                    'campo_estatico' => 0,
                ],
                [
                    'name' => 'dro_localidad',
                    'type' => 'input',
                    'description' => 'Localidad',
                    'description_rec' => '|+|',
                    'fundamento' => '',
                    'opciones' => '',
                    'opciones_desc' => '',
                    'step' => 4,
                    'secuencia' => 14,
                    'requerido' => 1,
                    'tipo_tramite' => 'oficial',
                    'status' => 1,
                    'id_municipio' => 0,
                    'editable' => 0,
                    'campo_estatico' => 0,
                ],
                [
                    'name' => 'dro_mpio',
                    'type' => 'input',
                    'description' => 'Municipio',
                    'description_rec' => '|+|',
                    'fundamento' => '',
                    'opciones' => '',
                    'opciones_desc' => '',
                    'step' => 4,
                    'secuencia' => 15,
                    'requerido' => 1,
                    'tipo_tramite' => 'oficial',
                    'status' => 1,
                    'id_municipio' => 0,
                    'editable' => 0,
                    'campo_estatico' => 0,
                ],
                [
                    'name' => 'dro_cp',
                    'type' => 'input',
                    'description' => 'CP',
                    'description_rec' => '|+|',
                    'fundamento' => '',
                    'opciones' => '',
                    'opciones_desc' => '',
                    'step' => 4,
                    'secuencia' => 16,
                    'requerido' => 1,
                    'tipo_tramite' => 'oficial',
                    'status' => 1,
                    'id_municipio' => 0,
                    'editable' => 0,
                    'campo_estatico' => 0,
                ],

                //informacion de la obra

                /*[
                    'name' => 'lic_vigencia',
                    'type' => 'input',
                    'description' => 'Vigencia',
                    'description_rec' => '|+|',
                    'fundamento' => '',
                    'opciones' => '',
                    'opciones_desc' => '',
                    'step' => 5,
                    'secuencia' => 1,
                    'requerido' => 1,
                    'tipo_tramite' => 'oficial',
                    'status' => 1,
                    'id_municipio' => 0,
                    'editable' => 0,
                    'campo_estatico' => 0,
                ],
                [
                    'name' => 'lic_vigencia_duracion',
                    'type' => 'select',
                    'description' => 'Duración',
                    'description_rec' => '',
                    'fundamento' => '',
                    'opciones' => 'Días|Meses',
                    'opciones_desc' => '1|2',
                    'step' => 5,
                    'secuencia' => 2,
                    'requerido' => 1,
                    'tipo_tramite' => 'oficial',
                    'status' => 1,
                    'id_municipio' => 0,
                    'editable' => 0,
                    'campo_estatico' => 0,
                ],
                [
                    'name' => 'exp_uso_suelo',
                    'type' => 'input',
                    'description' => 'Exp. Uso de suelo',
                    'description_rec' => '|+|',
                    'fundamento' => '',
                    'opciones' => '',
                    'opciones_desc' => '',
                    'step' => 5,
                    'secuencia' => 3,
                    'requerido' => 1,
                    'tipo_tramite' => 'oficial',
                    'status' => 1,
                    'id_municipio' => 0,
                    'editable' => 0,
                    'campo_estatico' => 0,
                ],
                [
                    'name' => 'lic_restri_pos',
                    'type' => 'input',
                    'description' => 'Restricción posterior',
                    'description_rec' => '|+|',
                    'fundamento' => '',
                    'opciones' => '',
                    'opciones_desc' => '',
                    'step' => 5,
                    'secuencia' => 4,
                    'requerido' => 1,
                    'tipo_tramite' => 'oficial',
                    'status' => 1,
                    'id_municipio' => 0,
                    'editable' => 0,
                    'campo_estatico' => 0,
                ],
                [
                    'name' => 'lic_restri_trasera',
                    'type' => 'input',
                    'description' => 'Restricción frontal',
                    'description_rec' => '|+|',
                    'fundamento' => '',
                    'opciones' => '',
                    'opciones_desc' => '',
                    'step' => 5,
                    'secuencia' => 5,
                    'requerido' => 1,
                    'tipo_tramite' => 'oficial',
                    'status' => 1,
                    'id_municipio' => 0,
                    'editable' => 0,
                    'campo_estatico' => 0,
                ],
                [
                    'name' => 'lic_restri_lat',
                    'type' => 'input',
                    'description' => 'Restricción lateral',
                    'description_rec' => '|+|',
                    'fundamento' => '',
                    'opciones' => '',
                    'opciones_desc' => '',
                    'step' => 5,
                    'secuencia' => 6,
                    'requerido' => 1,
                    'tipo_tramite' => 'oficial',
                    'status' => 1,
                    'id_municipio' => 0,
                    'editable' => 0,
                    'campo_estatico' => 0,
                ],*/
                [
                    'name' => 'lic_info_adicional',
                    'type' => 'input',
                    'description' => 'Información adicional',
                    'description_rec' => '|+|',
                    'fundamento' => '',
                    'opciones' => '',
                    'opciones_desc' => '',
                    'step' => 5,
                    'secuencia' => 1,
                    'requerido' => 1,
                    'tipo_tramite' => 'oficial',
                    'status' => 1,
                    'id_municipio' => 0,
                    'editable' => 0,
                    'campo_estatico' => 0,
                ],
            ]
        );
    }
}
