export class HistoricoLicenciias {
   public anio_licencia: string;
   public apellido_m: string;
   public apellido_p: string;
   public apellido_solicitante_m: string;
   public apellido_solicitante_p: string;
   public calle: string;
   public calle_predio: string
   public calle_solicitante: string;
   public calle_titular: string;
   public clave_catastral: string;
   public codigo_giro: string;
   public colonia: string;
   public colonia_predio: string;
   public colonia_titular: string;
   public coordonadas_x: string;
   public coordonadas_y: string;
   public cp_predio: string;
   public cp_solicitante: string;
   public cp_titular: string;
   public curp: string;
   public curp_solicitante: string;
   public deleted_at: string;
   public desc_act: string;
   public descripcion_detallada: string;
   public email: string;
   public email_solicitante: string;
   public fecha_emision: string;
   public fecha_pago: string;
   public folio_licencia: string;
   public giro: string;
   public hora_a: string;
   public hora_c: string;
   public horario: string;
   public id: number;
   public id_municipio: number;
   public id_usuario_pago: number;
   public inversion: number;
   public motivo: string;
   public nombre_negocio: string;
   public nombre_solicitante?: string;
   public nombre_titular: string;
   public num_ext_predio: string;
   public num_int_predio: string;
   public numero_cajones: string;
   public numero_empleado: string;
   public numero_ext: string;
   public numero_ext_titular: string;
   public numero_int: string;
   public numero_int_titular: string;
   public numero_lic: string;
   public razon_social: string;
   public referencia: string;
   public rfc: string;
   public rfc_solicitante: string;
   public status: number;
   public status_baja: number;
   public status_licencia: string;
   public status_pago: number;
   public step_1: number;
   public step_2: number;
   public step_3: number;
   public step_4: number;
   public superficie_giro: string;
   public telefono: string;
   public telefono_solicitante: string;
   public tipo_inmueble: string;
   public tipo_licencia: string;
   public updated_at: string;
   public url_minimapa: string;
   public venta_alcohol: string;
   constructor(
      info?
   ) {
      this.anio_licencia = info.anio_licencia || '';
      this.apellido_m = info.apellido_m || '';
      this.apellido_p = info.apellido_p || '';
      this.apellido_solicitante_m = info.apellido_solicitante_m || '';
      this.apellido_solicitante_p = info.apellido_solicitante_p || '';
      this.calle = info.calle || '';
      this.calle_predio = info.calle_predio || '';
      this.calle_solicitante = info.calle_solicitante || '';
      this.calle_titular = info.calle_titular || '';
      this.clave_catastral = info.clave_catastral || '';
      this.codigo_giro = info.codigo_giro || '';
      this.colonia = info.colonia || '';
      this.colonia_predio = info.colonia_predio || '';
      this.colonia_titular = info.colonia_titular || '';
      this.coordonadas_x = info.coordonadas_x || '';
      this.coordonadas_y = info.coordonadas_y || '';
      this.cp_predio = info.cp_predio || '';
      this.cp_solicitante = info.cp_solicitante || '';
      this.cp_titular = info.cp_titular || '';
      this.curp = info.curp || '';
      this.curp_solicitante = info.curp_solicitante || '';
      this.desc_act = info.desc_act || '';
      this.descripcion_detallada = info.descripcion_detallada || '';
      this.email = info.email || '';
      this.email_solicitante = info.email_solicitante || '';
      this.fecha_emision = info.fecha_emision || '';
      this.fecha_pago = info.fecha_pago || '';
      this.folio_licencia = info.folio_licencia || '';
      this.giro = info.giro || '';
      this.hora_a = info.hora_a || '';
      this.hora_c = info.hora_c || '';
      this.horario = info.horario || '';
      this.id = info.id || 0;
      this.id_municipio = info.id_municipio || 0;
      this.id_usuario_pago = info.id_usuario_pago || 0;
      this.inversion = info.inversion || '';
      this.motivo = info.motivo || '';
      this.nombre_negocio = info.nombre_negocio || '';
      this.nombre_solicitante = info.nombre_solicitante || '';
      this.nombre_titular = info.nombre_titular || '';
      this.num_ext_predio = info.num_ext_predio || '';
      this.num_int_predio = info.num_int_predio || '';
      this.numero_cajones = info.numero_cajones || '';
      this.numero_empleado = info.numero_empleado || '';
      this.numero_ext = info.numero_ext || '';
      this.numero_ext_titular = info.numero_ext_titular || '';
      this.numero_int = info.numero_int || '';
      this.numero_int_titular = info.numero_int_titular || '';
      this.numero_lic = info.numero_lic || '';
      this.razon_social = info.razon_social || '';
      this.referencia = info.referencia || '';
      this.rfc = info.rfc || '';
      this.rfc_solicitante = info.rfc_solicitante || '';
      this.status = info.status || '';
      this.status_baja = info.status_baja || '';
      this.status_licencia = info.status_licencia || '';
      this.status_pago = info.status_pago || '';
      this.step_1 = info.step_1 || '';
      this.step_2 = info.step_2 || '';
      this.step_3 = info.step_3 || '';
      this.step_4 = info.step_4 || '';
      this.superficie_giro = info.superficie_giro || '';
      this.telefono = info.telefono || '';
      this.telefono_solicitante = info.telefono_solicitante || '';
      this.tipo_inmueble = info.tipo_inmueble || '';
      this.tipo_licencia = info.tipo_licencia || '';
      this.updated_at = info.updated_at || '';
      this.url_minimapa = info.url_minimapa || '';
      this.venta_alcohol = info.venta_alcohol || '';

    
   }

}